from random import choice

words6 = ['absent', 'accent', 'accept', 'action', 'active', 'adjust', 'admire', 'advice', 'afford', 'agency', 'animal', 'apathy', 'appeal', 'arrest', 'artist', 'banner', 'barrel', 'basket', 'battle', 'behave', 'belief', 'belong', 'betray', 'bishop', 'bitter', 'bloody', 'border', 'bottle', 'bottom', 'breast', 'breeze', 'bronze', 'bubble', 'bucket', 'budget', 'buffet', 'bullet', 'bundle', 'burial', 'camera', 'cancel', 'cancer', 'candle', 'canvas', 'career', 'carpet', 'census', 'center', 'chance', 'charge', 'choose', 'circle', 'clinic', 'clique', 'closed', 'coffin', 'collar', 'colony', 'corner', 'couple', 'create', 'crisis', 'critic', 'crutch', 'damage', 'danger', 'deadly', 'decade', 'defend', 'depend', 'deport', 'deputy', 'design', 'detail', 'devote', 'dilute', 'dinner', 'divide', 'doctor', 'dragon', 'driver', 'effect', 'effort', 'elapse', 'endure', 'energy', 'ensure', 'estate', 'ethics', 'excess', 'excuse', 'exempt', 'expose', 'extort', 'facade', 'factor', 'finger', 'flavor', 'flawed', 'flower', 'forbid', 'forest', 'format', 'fossil', 'foster', 'friend', 'frozen', 'galaxy', 'gallon', 'garage', 'garlic', 'glance', 'global', 'gossip', 'gravel', 'ground', 'growth', 'grudge', 'guitar', 'hammer', 'harass', 'harbor', 'health', 'heaven', 'helmet', 'heroin', 'hiccup', 'honest', 'horror', 'hunter', 'ignite', 'immune', 'indoor', 'inject', 'insert', 'inside', 'instal', 'island', 'kidney', 'killer', 'labour', 'lawyer', 'layout', 'leader', 'legend', 'length', 'letter', 'likely', 'linear', 'listen', 'locate', 'lounge', 'makeup', 'marble', 'margin', 'master', 'matrix', 'memory', 'minute', 'mirror', 'mobile', 'modest', 'moment', 'morale', 'morsel', 'mosaic', 'mother', 'muscle', 'museum', 'mutter', 'mutual', 'narrow', 'nature', 'needle', 'notice', 'notion', 'offend', 'office', 'offset', 'option', 'orange', 'origin', 'outlet', 'packet', 'palace', 'parade', 'pastel', 'peanut', 'period', 'person', 'pierce', 'pigeon', 'pillow', 'planet', 'please', 'pledge', 'poetry', 'poison', 'policy', 'polite', 'preach', 'prefer', 'prince', 'profit', 'proper', 'quaint', 'rabbit', 'reader', 'reason', 'reduce', 'refund', 'regard', 'regret', 'remedy', 'remind', 'report', 'resign', 'result', 'retire', 'return', 'review', 'revise', 'revive', 'reward', 'rhythm', 'rocket', 'rotate', 'runner', 'sacred', 'salmon', 'scheme', 'school', 'screen', 'script', 'second', 'secure', 'series', 'sermon', 'settle', 'shiver', 'shower', 'singer', 'sleeve', 'slogan', 'smooth', 'sodium', 'speech', 'sphere', 'spider', 'spirit', 'spread', 'spring', 'square', 'strict', 'strike', 'string', 'stroke', 'studio', 'subway', 'suntan', 'survey', 'switch', 'symbol', 'system', 'tablet', 'tender', 'thanks', 'thread', 'threat', 'tongue', 'topple', 'trench', 'tumble', 'tumour', 'tycoon', 'unfair', 'unlike', 'unrest', 'update', 'valley', 'velvet', 'vessel', 'virtue', 'visual', 'volume', 'voyage', 'wander', 'window', 'winner', 'winter', 'wonder']

words5 = ['disco', 'angel', 'heavy', 'brain', 'basin', 'eject', 'union', 'radio', 'brown', 'trunk', 'image', 'white', 'crowd', 'pupil', 'enjoy', 'widen', 'trait', 'relax', 'money', 'humor', 'blast', 'elite', 'tease', 'great', 'cycle', 'bread', 'flock', 'young', 'shift', 'glory', 'spare', 'stand', 'dairy', 'table', 'charm', 'truth', 'pause', 'yearn', 'tread', 'braid', 'tract', 'wheat', 'waist', 'glide', 'novel', 'state', 'amuse', 'house', 'bleed', 'board', 'model', 'crack', 'false', 'hover', 'seize', 'smell', 'beard', 'steam', 'lodge', 'virus', 'blind', 'snarl', 'snack', 'clerk', 'arena', 'score', 'force', 'blade', 'build', 'guilt', 'bless', 'truck', 'carve', 'think', 'chief', 'essay', 'irony', 'video', 'delay', 'tribe', 'court', 'guard', 'salon', 'dozen', 'elect', 'refer', 'angle', 'strip', 'teach', 'chain', 'start', 'sight', 'block', 'scale', 'organ', 'scrap', 'train', 'short', 'width', 'dream', 'shame', 'utter', 'steep', 'stall', 'berry', 'Bible', 'ratio', 'glove', 'track', 'storm', 'anger', 'cover', 'begin', 'embox', 'clock', 'place', 'layer', 'power', 'shell', 'orbit', 'panel', 'shark', 'abbey', 'rebel', 'theft', 'cabin', 'stock', 'muggy', 'drain', 'noise', 'break', 'mouse', 'proud', 'grand', 'exact', 'bring', 'bitch', 'leave', 'light', 'south', 'story', 'chord', 'drink', 'forum', 'album', 'blame', 'weave', 'shake', 'cruel', 'color', 'flood', 'opera', 'sting', 'lunch', 'laser', 'crash', 'snail', 'clash', 'ankle', 'reach', 'throw', 'gloom', 'fault', 'field', 'woman', 'whole', 'slant', 'adopt', 'rumor', 'swear', 'sheet', 'sword', 'slime', 'bride', 'alarm', 'Koran', 'exile', 'spill', 'grace', 'ivory', 'agile', 'faint', 'prove', 'draft', 'dough', 'harsh', 'proof', 'clean', 'punch', 'smart', 'uncle', 'quiet', 'sheep', 'scene', 'feast', 'grass', 'admit', 'fling', 'steel', 'coast', 'amber', 'rough', 'queen', 'chest', 'basic', 'order', 'flesh', 'handy', 'taste', 'fresh', 'bacon', 'check', 'youth', 'index', 'gaffe', 'wreck', 'budge', 'shape', 'jelly', 'value', 'arrow', 'black', 'acute', 'grain', 'crude', 'stool', 'float', 'voter', 'urine', 'enemy', 'child', 'suite', 'outer', 'sleep', 'plant', 'Venus', 'breed', 'paper', 'sport', 'ample', 'haunt', 'deter', 'major', 'grant', 'route', 'fleet', 'fever', 'stuff', 'slump', 'night', 'water', 'speed', 'close', 'fibre', 'giant', 'river', 'claim', 'robot', 'tasty', 'smash', 'creed', 'nerve', 'heart', 'funny', 'alive', 'ready', 'prize', 'stake', 'curve', 'party', 'doubt', 'X-ray', 'large', 'ferry', 'stamp', 'eagle', 'motif', 'price', 'plain', 'trend', 'sweep', 'frown', 'shave', 'cross', 'miner', 'shoot', 'guess', 'toast', 'class', 'bench', 'brick', 'trick', 'split', 'patch', 'honor', 'sweat']

words7 = ['impress', 'whisper', 'journal', 'illness', 'teacher', 'opinion', 'relieve', 'passage', 'overall', 'episode', 'hostile', 'pension', 'passion', 'capture', 'perfume', 'stomach', 'harmful', 'posture', 'venture', 'payment', 'testify', 'jealous', 'portion', 'dynamic', 'looting', 'anxiety', 'chicken', 'mystery', 'village', 'fortune', 'forward', 'measure', 'release', 'current', 'equinox', 'laborer', 'fixture', 'radical', 'enhance', 'display', 'pyramid', 'visible', 'torture', 'trainer', 'quality', 'feather', 'capital', 'dismiss', 'retiree', 'reactor', 'process', 'century', 'feeling', 'edition', 'glasses', 'inquiry', 'absence', 'convict', 'shatter', 'arrange', 'strange', 'balance', 'speaker', 'cluster', 'variant', 'trivial', 'revenge', 'compact', 'thinker', 'develop', 'trouser', 'justify', 'tension', 'penalty', 'diamond', 'vehicle', 'trustee', 'address', 'haircut', 'divorce', 'network', 'retired', 'wedding', 'company', 'bathtub', 'pudding', 'pioneer', 'licence', 'express', 'opposed', 'abridge', 'neutral', 'related', 'trouble', 'costume', 'chapter', 'formula', 'terrace', 'harvest', 'swallow', 'patient', 'kitchen', 'clarify', 'husband', 'passive', 'channel', 'prevent', 'promise', 'convert', 'extreme', 'explain', 'voucher', 'message', 'peasant', 'grounds', 'retreat', 'approve', 'lineage', 'glacier', 'outline', 'banquet', 'assault', 'package', 'general', 'mention', 'finance', 'breathe', 'chimney', 'wrestle', 'veteran', 'captain', 'courage', 'benefit', 'dribble', 'monarch', 'nursery', 'lighter', 'offense', 'hallway', 'college', 'deprive', 'decline', 'embrace', 'soldier', 'inspire', 'monster', 'quarter', 'hunting', 'freckle', 'article', 'compose', 'insight', 'endorse', 'outlook', 'initial', 'certain', 'plaster', 'auditor', 'stadium', 'ecstasy', 'officer', 'liberal', 'laundry', 'central', 'fiction', 'support', 'meeting' 'society', 'enlarge', 'applied', 'drawing', 'suspect', 'maximum', 'concern', 'scandal', 'concert', 'charter', 'snuggle', 'reality', 'pursuit', 'welcome', 'serious', 'biology', 'partner', 'royalty', 'cunning', 'pasture', 'reverse', 'realize', 'protest', 'manager', 'leaflet', 'horizon', 'auction', 'sulphur', 'lecture', 'improve', 'project', 'protect', 'obscure', 'glimpse', 'apology', 'reptile', 'archive', 'suggest', 'paradox', 'splurge', 'predict', 'discuss', 'command', 'combine', 'privacy', 'dilemma', 'funeral', 'content', 'shelter', 'receipt', 'despise', 'limited', 'volcano', 'surgeon', 'contact', 'precede', 'abandon', 'soprano', 'elegant', 'kinship', 'stretch', 'sustain', 'bargain', 'promote', 'similar', 'exclude', 'distant', 'tourist', 'musical', 'reserve', 'housing', 'contain', 'council', 'biscuit', 'counter', 'context']

def pickWord(len):
    try:
        if len == 5:
            word = choice(words5)
        elif len == 6:
            word = choice(words6)
        elif len == 7:
            word = choice(words7)
        return word
    except UnboundLocalError:
        return "Input Error"

if __name__ == "__main__":
    lenth = int(input("Enter lenth -->"))
    while lenth != 66:
        print(pickWord(lenth))
        lenth = int(input("Enter lenth -->"))